# Generated by Django 2.0.2 on 2019-07-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='bimage',
            new_name='image',
        ),
    ]
